### ISSUE TITLE
#EXT-OATCLS-SCTE35 tag is getting removed

### ISSUE THREAD

**Issue by piyushchourasiya** [globocom/m3u8#183]
According to documentation, this library supports the '#EXT-OATCLS-SCTE35' tag. But, 
when I used this parser to trim manifest files, SCTE tags were getting removed.

Below are the steps I follow,
1. Downloaded master manifest file[using python request]
2. Passed downloaded master manifest string to m3u8.loads method and got parsed master manifest object[say parsed_master_manifest]
3. Iterated over playlists of parsed_master_manifest
    a. Downloaded child manifest file[using python request]
    b. Passed downloaded child manifest string to m3u8.loads method and got parsed child manifest object[say parsed_child_manifest]
    c. Initialized Segmentlist[say desired_segments]
    d. Appended desired segments in  desired_segments
    e. Replaced original segments list with desired_segments
4. Store Master and all child manifest on local machine using m3u8.dump method
 
Please expedite this. and me know If I am doing anything wrong. I would much appreciate if any of you suggest a solution for this.

**Comment by davemevans** [comment]
Handling in this case means the library can parse these tags and return useful information from them, but not necessarily  dumped.

I'm just working on improvements to SCTE tag handling so that EXT-X-CUE-OUT and EXT-X-CUE-IN are handled properly and dumped correctly.

I will probably PR this later. However, I wasn't planning to include EXT-OATCLS-SCTE35 since this is not a use case for us.

**Comment by piyushchourasiya** [comment]
@davemevans thanks for the revert. Should I make the required changes and raise PR if it is fine.

**Comment by futzu** [comment]
Gentlemen, I have a SCTE35  parser and I could use a m3u8 parser, we should collaborate. 
 https://github.com/futzu/SCTE35-threefive
