### ISSUE TITLE
Playlist objects can't be used with add_playlist()

### ISSUE THREAD

**Issue by Baa14453** [globocom/m3u8#361]
Essentially I am building a variant playlist by combining normal playlists:
```py
files = listdir(input_playlists_directory)
m3u8_files = []

# Get a list of playlist files and their full path.
for file in files:
    if file.endswith(".m3u8"):
        m3u8_files.append(input_playlists_directory.rstrip("/\\") + "/" + file)

# Create a new Playlist object
master_playlist = m3u8.model.M3U8()

# Append each playlist to the master playlist
for playlist in m3u8_files:
    # Load the playlist path into a Playlist object.
    playlist = m3u8.load(playlist)
    
    # Append to the master playlist
    master_playlist.add_playlist(playlist)
```

This seemed logical to me, but the result produced a text file with object references in it:
```
#EXTM3U
<m3u8.model.M3U8 object at 0x7a2f5452aaa0>
<m3u8.model.M3U8 object at 0x7a2f5452ab60>
<m3u8.model.M3U8 object at 0x7a2f5452abc0>
<m3u8.model.M3U8 object at 0x7a2f5452ab30>
```

**Comment by davemevans** [comment]
`load` returns `M3U8` objects but `add_playlist` expects [`Playlist`](https://github.com/globocom/m3u8/blob/3c352ffd738cfa630c11a6920a9fbc605fc2a047/m3u8/model.py#L939) objects.

You could argue this could fail more gracefully, but what you are trying to do isn't correct.

**Comment by bbayles** [comment]
I don't think this is something you can really do, because the media playlists don't contain the information you  need to assemble a multivariant playlist.

Let's take [this stream](https://players.akamai.com/players/hlsjs?streamUrl=https%3A%2F%2Fcph-p2p-msl.akamaized.net%2Fhls%2Flive%2F2000341%2Ftest%2Fmaster.m3u8) for example.

Its media playlists look like this (shortened for clarity):

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:5849701
#EXTINF:6.000000,
segment_4_20240417_1713385074.ts
#EXTINF:6.000000,
segment_4_20240417_1713385081.ts
#EXTINF:6.000000,
segment_4_20240417_1713385086.ts
#EXTINF:6.000000,
segment_4_20240417_1713385092.ts
#EXTINF:6.000000,
segment_4_20240417_1713385099.ts
#EXTINF:6.000000,
segment_4_20240417_1713385104.ts
```

Its multivariant playlist looks like this (shortened for clarity):

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=550172,RESOLUTION=256x106
level_0.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1650064,RESOLUTION=640x266
level_1.m3u8
```

There's not any information about bandwidth or resolution in the media playlists that would allow you to construct the multivariant playlist. That would need to come from another source.

**Comment by Baa14453** [comment]
Ah that's a pain, oh well thank you both :heart: 
I'll construct the rest of the info manually and call add_playlist based on that.
